/* ============================================================
   TRAINING GROUNDS DATA — Daily Duel · Boss Battles ·
   Derivation Chain · Feynman Teach-Back · Formula Clock ·
   Campaign Mode. Consumed by window.TRAINING. All physics
   double-checked; zero PYQ photocopies.
   ============================================================ */
window.TRAINING = window.TRAINING || {};
window.TRAINING.DATA = {

/* ---------------- FORMULA CLOCK (high-yield, subject-tagged) ---------------- */
FORMULAS: [
 {s:"Quantum", f:"λ = h/p  (de Broglie wavelength)"},
 {s:"Quantum", f:"Δx·Δp ≥ ħ/2  (Heisenberg)"},
 {s:"Quantum", f:"Ĥψ = Eψ  (time-independent Schrödinger)"},
 {s:"Quantum", f:"Eₙ = n²π²ħ²/(2mL²)  (infinite well)"},
 {s:"Quantum", f:"Eₙ = (n + ½)ħω  (harmonic oscillator)"},
 {s:"Quantum", f:"Eₙ = −13.6 eV/n²  (hydrogen)"},
 {s:"Quantum", f:"[x̂, p̂] = iħ"},
 {s:"Quantum", f:"ΔE·Δt ≥ ħ/2  (energy–time)"},
 {s:"Quantum", f:"T ≈ e^(−2κa)  (tunnelling)"},
 {s:"Quantum", f:"∮p dx = (n + ½)h  (WKB quantisation)"},
 {s:"Atomic", f:"a₀ ≈ 0.529 Å  (Bohr radius)"},
 {s:"Atomic", f:"α = e²/(4πε₀ħc) ≈ 1/137"},
 {s:"Atomic", f:"μ_B = eħ/2m  (Bohr magneton)"},
 {s:"Atomic", f:"Δl = ±1  (electric-dipole selection rule)"},
 {s:"Nuclear", f:"R = R₀A^(1/3),  R₀ ≈ 1.2 fm"},
 {s:"Nuclear", f:"A = λN,  T₁/₂ = ln2/λ"},
 {s:"Nuclear", f:"B/A peak ≈ 8.8 MeV near Fe-56"},
 {s:"Nuclear", f:"d + t → ⁴He + n  (17.6 MeV)"},
 {s:"Nuclear", f:"Magic numbers: 2, 8, 20, 28, 50, 82, 126"},
 {s:"Thermo", f:"η_Carnot = 1 − T_c/T_h"},
 {s:"Thermo", f:"S = k ln Ω  (Boltzmann entropy)"},
 {s:"Thermo", f:"F = −kT ln Z"},
 {s:"Thermo", f:"Z = Σ e^(−βEᵢ)  (partition function)"},
 {s:"Thermo", f:"⟨n⟩_BE = 1/(e^(β(ε−μ)) − 1)"},
 {s:"Thermo", f:"⟨n⟩_FD = 1/(e^(β(ε−μ)) + 1)"},
 {s:"Thermo", f:"E_F = (ħ²/2m)(3π²n)^(2/3)"},
 {s:"Thermo", f:"v_mp = √(2kT/m)  (most probable speed)"},
 {s:"Thermo", f:"½kT per quadratic degree of freedom"},
 {s:"Thermo", f:"dP/dT = L/(TΔv)  (Clausius–Clapeyron)"},
 {s:"Thermo", f:"C_P − C_V = T V α²/κ_T"},
 {s:"Thermo", f:"F = C − P + 2  (Gibbs phase rule)"},
 {s:"Thermo", f:"u ∝ T⁴,  E = σT⁴  (Stefan–Boltzmann)"},
 {s:"Thermo", f:"λ_max·T ≈ 2.9×10⁻³ m·K  (Wien)"},
 {s:"Solid", f:"nλ = 2d sinθ  (Bragg)"},
 {s:"Solid", f:"C ∝ T³  (Debye, low T)"},
 {s:"Solid", f:"C = 3R  (Dulong–Petit, high T)"},
 {s:"Solid", f:"σ = ne²τ/m  (Drude conductivity)"},
 {s:"Solid", f:"λ_L ∝ n_s^(−1/2)  (London penetration)"},
 {s:"Solid", f:"BCC ↔ FCC  (reciprocal lattices)"},
 {s:"Solid", f:"m* = ħ²/(d²E/dk²)  (effective mass)"},
 {s:"EM", f:"∮E·dA = Q/ε₀  (Gauss)"},
 {s:"EM", f:"∇·B = 0  (no monopoles)"},
 {s:"EM", f:"∇×E = −∂B/∂t  (Faraday)"},
 {s:"EM", f:"∇×B = μ₀J + μ₀ε₀∂E/∂t  (Ampère–Maxwell)"},
 {s:"EM", f:"F = q(E + v×B)  (Lorentz)"},
 {s:"EM", f:"S = E×H  (Poynting vector)"},
 {s:"EM", f:"δ = √(2/(μσω))  (skin depth)"},
 {s:"EM", f:"f_c = (c/2)√((m/a)²+(n/b)²)  (waveguide cutoff)"},
 {s:"EM", f:"P = q²a²/(6πε₀c³)  (Larmor)"},
 {s:"EM", f:"B = μ₀I/(2R)  (loop centre)"},
 {s:"Classical", f:"L = T − V  (Lagrangian)"},
 {s:"Classical", f:"T = 2π√(L/g)  (pendulum)"},
 {s:"Classical", f:"I = 2MR²/5  (solid sphere)"},
 {s:"Classical", f:"γ = 1/√(1 − v²/c²)  (Lorentz factor)"},
 {s:"Classical", f:"E = mc²"},
 {s:"Classical", f:"E² = p²c² + m²c⁴"},
 {s:"Classical", f:"2⟨T⟩ = −⟨r·∇V⟩  (virial theorem)"},
 {s:"Classical", f:"{qᵢ, pⱼ} = δᵢⱼ  (Poisson bracket)"},
 {s:"Math", f:"∇×(∇φ) = 0"},
 {s:"Math", f:"∇·(∇×A) = 0"},
 {s:"Math", f:"∫δ(x)dx = 1"},
 {s:"Math", f:"F[δ(x)] = 1  (Fourier transform)"},
 {s:"Math", f:"Res ∮ f dz = 2πi Σ Res(f)"},
 {s:"Math", f:"e^(iθ) = cosθ + i sinθ  (Euler)"},
 {s:"Math", f:"⟨x²⟩ = 2Dt  (1D diffusion)"},
 {s:"Math", f:"Γ(n+1) = n!"},
 {s:"Electronics", f:"A_v = −R_f/R_in  (inverting op-amp)"},
 {s:"Electronics", f:"A_v = 1 + R_f/R₁  (non-inverting op-amp)"},
 {s:"Electronics", f:"f = 1/(2π√LC)  (resonance)"},
 {s:"Electronics", f:"NAND and NOR are universal gates"},
 {s:"Electronics", f:"|Aβ| = 1, ∠Aβ = 2πn  (Barkhausen)"}
],

/* ---------------- DAILY DUEL (one question a day, streak-tracked) ---------------- */
DUEL_QUESTIONS: [
 {lane:"quantum", q:"The ground-state energy of a particle of mass m in a one-dimensional infinite square well of width L is", o:["π²ħ²/(2mL²)","π²ħ²/(mL²)","π²ħ²/(4mL²)","ħ²/(2mL²)"], a:0, x:"Eₙ = n²π²ħ²/(2mL²); n = 1 gives π²ħ²/(2mL²)."},
 {lane:"quantum", q:"The zero-point energy of a one-dimensional quantum harmonic oscillator is", o:["ħω","ħω/2","3ħω/2","zero"], a:1, x:"Eₙ = (n + ½)ħω, so E₀ = ħω/2."},
 {lane:"solidstate", q:"The Fermi energy of a 3D free electron gas scales with electron density n as", o:["n","n^(1/3)","n^(2/3)","n^(3/2)"], a:2, x:"E_F = (ħ²/2m)(3π²n)^(2/3) ∝ n^(2/3)."},
 {lane:"thermo", q:"Bose–Einstein condensation in 3D occurs when", o:["the chemical potential reaches the ground-state energy","the temperature reaches absolute zero","the gas becomes classical","the pressure vanishes"], a:0, x:"Condensation begins when μ approaches the ground-state energy and a macroscopic fraction occupies the lowest state."},
 {lane:"atnuc", q:"Ignoring spin, the degeneracy of the hydrogen level with principal quantum number n is", o:["n","2n","n²","2n²"], a:2, x:"Each n has l = 0…n−1 and m = −l…l, totalling n² states."},
 {lane:"quantum", q:"The commutator [x̂, p̂] equals", o:["iħ","−iħ","ħ","zero"], a:0, x:"The fundamental commutation relation is [x̂,p̂] = iħ."},
 {lane:"quantum", q:"The possible eigenvalues of S_z for a spin-½ particle are", o:["0 only","±ħ/2","±ħ","ħ/2 only"], a:1, x:"For s = ½, m_s = ±½, so S_z = ±ħ/2."},
 {lane:"thermo", q:"The efficiency of a Carnot engine operating between 300 K and 400 K is", o:["20%","25%","33%","50%"], a:1, x:"η = 1 − 300/400 = 0.25 = 25%."},
 {lane:"thermo", q:"The most probable speed of a molecule of mass m at temperature T (Maxwell distribution) is", o:["√(3kT/m)","√(8kT/πm)","√(2kT/m)","√(kT/m)"], a:2, x:"v_mp = √(2kT/m)."},
 {lane:"solidstate", q:"At low temperature the lattice heat capacity of an insulator follows the Debye law", o:["C ∝ T","C ∝ T²","C ∝ T³","C ∝ e^(−Θ/T)"], a:2, x:"Debye: C_V ∝ T³ at low T."},
 {lane:"solidstate", q:"The reciprocal lattice of a BCC lattice is", o:["BCC","FCC","HCP","simple cubic"], a:1, x:"BCC and FCC are reciprocal to each other."},
 {lane:"solidstate", q:"Bragg's law for constructive interference is", o:["nλ = 2d sinθ","nλ = d sinθ","2nλ = d cosθ","λ = 2d cosθ"], a:0, x:"Constructive interference when the path difference 2d sinθ equals nλ."},
 {lane:"classical", q:"The Lorentz factor for v = 0.6c is", o:["1.15","1.25","1.67","2.00"], a:1, x:"γ = 1/√(1−0.36) = 1/0.8 = 1.25."},
 {lane:"atnuc", q:"The rest energy of an electron is approximately", o:["0.511 MeV","1.022 MeV","13.6 eV","938 MeV"], a:0, x:"m_e c² ≈ 0.511 MeV."},
 {lane:"atnuc", q:"In β⁻ decay a neutron converts into", o:["proton + electron + antineutrino","proton + positron + neutrino","proton + electron only","proton + photon"], a:0, x:"n → p + e⁻ + ν̄_e, conserving charge and lepton number."},
 {lane:"atnuc", q:"The binding energy per nucleon is a maximum near", o:["Hydrogen (A=1)","Helium (A=4)","Iron (A≈56)","Uranium (A≈238)"], a:2, x:"The B/A curve peaks near iron, A ≈ 56."},
 {lane:"atnuc", q:"The energy released in deuterium–tritium fusion is about", o:["2.2 MeV","17.6 MeV","200 MeV","0.511 MeV"], a:1, x:"d + t → ⁴He + n releases ≈ 17.6 MeV."},
 {lane:"atnuc", q:"Which of the following is a nuclear magic number?", o:["6","14","28","32"], a:2, x:"Magic numbers are 2, 8, 20, 28, 50, 82, 126."},
 {lane:"atnuc", q:"Rutherford's differential scattering cross-section is proportional to", o:["1/sin⁴(θ/2)","1/sin²(θ/2)","sin⁴(θ/2)","cos²(θ/2)"], a:0, x:"dσ/dΩ ∝ 1/sin⁴(θ/2) for Coulomb scattering."},
 {lane:"quantum", q:"To first order, the energy correction of a non-degenerate state |n⟩ under a perturbation H′ is", o:["⟨n|H′|n⟩","Σ|⟨m|H′|n⟩|²/(Eₙ−Eₘ)","−⟨n|H′|n⟩","zero"], a:0, x:"First-order non-degenerate correction is the diagonal element ⟨n|H′|n⟩."},
 {lane:"quantum", q:"The variational method yields a ground-state energy estimate that is", o:["always an upper bound","always a lower bound","exact for any trial function","unrelated to the true energy"], a:0, x:"⟨H⟩ ≥ E₀ for any trial wavefunction."},
 {lane:"quantum", q:"The WKB (Bohr–Sommerfeld) quantisation condition is", o:["∮p dx = nh","∮p dx = (n+½)h","∮p dx = (n+1)h","∮p dx = 2nπħ"], a:1, x:"WKB: ∮p dx = (n + ½)h."},
 {lane:"solidstate", q:"The London penetration depth of a superconductor scales with superfluid density n_s as", o:["n_s^(−1/2)","n_s^(1/2)","n_s^(−1)","n_s"], a:0, x:"λ_L = √(m/(μ₀n_s e²)) ∝ n_s^(−1/2)."},
 {lane:"solidstate", q:"The Meissner effect is the", o:["expulsion of magnetic flux from a superconductor","zero resistance below T_c","creation of Cooper pairs","quantisation of flux in units of h/e"], a:0, x:"Below T_c a superconductor expels magnetic flux (perfect diamagnetism, χ = −1)."},
 {lane:"quantum", q:"For identical fermions the total wavefunction must be", o:["antisymmetric under exchange","symmetric under exchange","a simple product state","always real"], a:0, x:"Pauli principle: the fermion wavefunction is antisymmetric under exchange."},
 {lane:"mathphys", q:"The Fourier transform of the Dirac delta function δ(x) is", o:["1","e^(−k²)","sin(k)/k","δ(k)"], a:0, x:"∫δ(x)e^(−ikx)dx = 1."},
 {lane:"mathphys", q:"The eigenvalues of any Pauli matrix are", o:["±1","±i","0 and 1","±ħ/2"], a:0, x:"Each Pauli matrix squares to the identity, so its eigenvalues are ±1."},
 {lane:"mathphys", q:"The magnitude of the gradient of 1/r is", o:["1/r²","1/r","2/r²","−1/r"], a:0, x:"∇(1/r) = −r̂/r², magnitude 1/r²."},
 {lane:"atnuc", q:"The Larmor precession angular frequency of a magnetic moment μ in a field B is", o:["μB/ħ","ħμ/B","μ/(ħB)","B/(μħ)"], a:0, x:"ω_L = μB/ħ from the torque μ×B."},
 {lane:"classical", q:"A muon (mean lifetime 2.2 μs at rest) moves with γ = 10. Its lab-frame lifetime is", o:["2.2 μs","22 μs","220 μs","0.22 μs"], a:1, x:"Time dilation: t = γτ = 10 × 2.2 = 22 μs."},
 {lane:"emtheory", q:"The skin depth in a good conductor, as frequency increases,", o:["increases","decreases","stays constant","vanishes at DC"], a:1, x:"δ = √(2/(μσω)) decreases with frequency."},
 {lane:"emtheory", q:"The magnetic field at the centre of a circular current loop of radius R is", o:["μ₀I/(2R)","μ₀I/(4R)","μ₀I/R","μ₀I/(2πR)"], a:0, x:"Biot–Savart integration gives B = μ₀I/(2R)."},
 {lane:"electronics", q:"The voltage gain of an ideal inverting op-amp with R_f and R_in is", o:["−R_f/R_in","R_f/R_in","1 + R_f/R_in","−R_in/R_f"], a:0, x:"V_out = −(R_f/R_in)V_in."},
 {lane:"electronics", q:"For an ideal half-wave rectifier with a sinusoidal input of peak 10 V, the average output is about", o:["3.18 V","5 V","6.37 V","10 V"], a:0, x:"V_avg = V_peak/π = 10/π ≈ 3.18 V."}
],

/* ---------------- DERIVATION CHAIN (fill the gap) ---------------- */
DERIVATIONS: [
 {id:"timedilation", title:"Time dilation (light clock)", lane:"classical", steps:[
  {p:"A light clock has mirrors distance d apart; the round-trip proper time is Δτ = 2d/c. For a moving observer the light path is longer, giving (cΔt/2)² = d² + ( ____ )².", o:["vΔt/2","vΔt","cΔt/2","d"], a:0, n:"The mirror moves vΔt/2 horizontally while light crosses."},
  {p:"Using (cΔt)² = (2d)² + (vΔt)² with 2d = cΔτ gives Δt = ____ .", o:["Δτ√(1−v²/c²)","Δτ/√(1−v²/c²)","Δτ(1−v²/c²)","Δτ(1+v²/c²)"], a:1, n:"Solve for Δt: Δt = Δτ/√(1−v²/c²)."},
  {p:"The factor multiplying Δτ is the Lorentz factor γ = ____ .", o:["1/√(1−v²/c²)","√(1−v²/c²)","1−v²/c²","1/√(1+v²/c²)"], a:0, n:"γ = 1/√(1−v²/c²)."},
  {p:"Physical consequence: moving clocks run ____ .", o:["slow","fast","at the same rate","backwards"], a:0, n:"Moving clocks tick slower — time dilation."}
 ]},
 {id:"compton", title:"Compton wavelength shift", lane:"atnuc", steps:[
  {p:"Conserving 4-momentum in photon–electron scattering and eliminating the electron momentum gives λ′ − λ = (h/mc)(1 − ____ ).", o:["cosθ","sinθ","tanθ","cos(θ/2)"], a:0, n:"The shift depends on 1 − cosθ."},
  {p:"The constant h/mc is the Compton wavelength of the ____ .", o:["electron","proton","neutron","photon"], a:0, n:"It is h/(m_e c) ≈ 2.43×10⁻¹² m."},
  {p:"Numerically the electron Compton wavelength is about ____ m.", o:["2.43×10⁻¹²","1.23×10⁻¹²","3.86×10⁻¹³","5.29×10⁻¹¹"], a:0, n:"λ_C = h/(m_e c) ≈ 2.43 pm."},
  {p:"The maximum shift occurs at backscattering θ = 180°, and equals ____ .", o:["2h/(mc)","h/(mc)","h/(2mc)","zero"], a:0, n:"1 − cos180° = 2, so Δλ = 2h/(mc)."}
 ]},
 {id:"bohr", title:"Bohr radius", lane:"atnuc", steps:[
  {p:"Balancing Coulomb attraction with centripetal force in the Bohr model: mv²/r = ____ .", o:["e²/(4πε₀r²)","e²/(4πε₀r)","m/r²","e/(4πε₀r²)"], a:0, n:"Coulomb force = centripetal force."},
  {p:"Angular-momentum quantisation in the Bohr model: mvr = ____ .", o:["nħ","n²ħ","ħ/2","nπħ"], a:0, n:"mvr = nħ (n = 1,2,3,…)."},
  {p:"Eliminating v gives orbit radii rₙ = n²a₀ with a₀ = ____ .", o:["4πε₀ħ²/(me²)","me²/(4πε₀ħ²)","ħ/(m e c)","4πε₀ħ/(me)"], a:0, n:"a₀ = 4πε₀ħ²/(me²)."},
  {p:"Numerically the Bohr radius is about ____ Å.", o:["0.529","1.06","2.12","13.6"], a:0, n:"a₀ ≈ 0.529 Å."}
 ]},
 {id:"fermidirac", title:"Fermi–Dirac distribution", lane:"thermo", steps:[
  {p:"Maximising entropy under fixed mean particle number and energy introduces a Lagrange multiplier ____ (the chemical potential) for particle number.", o:["μ","T","P","β"], a:0, n:"μ fixes the mean occupation."},
  {p:"The mean occupation of a level ε for fermions is ⟨n⟩ = ____ .", o:["1/(e^(β(ε−μ)) + 1)","1/(e^(β(ε−μ)) − 1)","e^(−β(ε−μ))","1/(1 − e^(−β(ε−μ)))"], a:0, n:"Fermi–Dirac has +1 in the denominator."},
  {p:"At T = 0 the distribution is a step: 1 for ε < μ and ____ for ε > μ.", o:["0","1/2","1","e^(−βε)"], a:0, n:"Occupied up to μ, empty above."},
  {p:"For bosons the denominator has ____ instead of +1.", o:["−1","+2","0","+1/2"], a:0, n:"Bose–Einstein: ⟨n⟩ = 1/(e^(β(ε−μ)) − 1)."}
 ]},
 {id:"partition", title:"Partition function → energy", lane:"thermo", steps:[
  {p:"The canonical partition function is Z = ____ .", o:["Σ e^(−βEᵢ)","Σ Eᵢ e^(−βEᵢ)","∫ e^(−βE)dE","Σ ln(e^(−βEᵢ))"], a:0, n:"Sum of Boltzmann factors."},
  {p:"The Helmholtz free energy is F = ____ .", o:["−kT ln Z","kT ln Z","−kT Z","kT/Z"], a:0, n:"F = −kT ln Z."},
  {p:"The mean energy is U = −∂ ln Z/∂β = ____ .", o:["Σ Eᵢ e^(−βEᵢ)/Z","Σ e^(−βEᵢ)","kT ln Z","−Σ ln Eᵢ"], a:0, n:"The Boltzmann-weighted average."},
  {p:"The energy fluctuation is (ΔE)² = ____ .", o:["kT²C_V","kTC_V","kT²/C_V","kT C_V²"], a:0, n:"(ΔE)² = kT²C_V."}
 ]},
 {id:"clapeyron", title:"Clausius–Clapeyron equation", lane:"thermo", steps:[
  {p:"At phase coexistence the specific Gibbs free energies are equal: g₁(T,P) = ____ .", o:["g₂(T,P)","s₁","v₂","μ₁ + μ₂"], a:0, n:"Equilibrium requires equal chemical potentials."},
  {p:"Using dg = −s dT + v dP, equality along the coexistence line gives (s₂ − s₁)dT = ____ .", o:["(v₂ − v₁)dP","(v₁ − v₂)dP","(s₂ − s₁)dP","(v₂ + v₁)dP"], a:0, n:"−s₁dT + v₁dP = −s₂dT + v₂dP."},
  {p:"The entropy difference equals L/T, so the slope is dP/dT = ____ .", o:["L/(TΔv)","TΔv/L","LΔv/T","T/(LΔv)"], a:0, n:"Clausius–Clapeyron: dP/dT = L/(TΔv)."},
  {p:"For ice–water, Δv = v_water − v_ice < 0, so the melting curve has ____ slope.", o:["negative","positive","zero","infinite"], a:0, n:"Ice is less dense than water."}
 ]},
 {id:"kepler", title:"Kepler's third law (circular orbit)", lane:"classical", steps:[
  {p:"For a circular orbit, gravity provides the centripetal force: GMm/r² = ____ .", o:["mv²/r","mv/r","mωr","mg"], a:0, n:"Centripetal force mv²/r."},
  {p:"Writing v = 2πr/T and substituting gives GM/r² = ____ .", o:["4π²r/T²","2πr/T²","4πr²/T","2π²r/T"], a:0, n:"v² = 4π²r²/T²."},
  {p:"Rearranging for the period: T² = ____ .", o:["4π²r³/(GM)","4π²r²/(GM)","GM/(4π²r³)","2πr³/(GM)"], a:0, n:"Kepler's third law."},
  {p:"Hence T² ∝ ____ .", o:["r³","r²","r","√r"], a:0, n:"The square of the period scales as the cube of the radius."}
 ]},
 {id:"oscillator", title:"Harmonic-oscillator ladder", lane:"quantum", steps:[
  {p:"With a ∝ (x̂ + i p̂/mω), the Hamiltonian becomes Ĥ = ħω( ____ ).", o:["a†a + ½","a†a","aa†","a†a − ½"], a:0, n:"Ĥ = ħω(a†a + ½)."},
  {p:"The commutation relation of the ladder operators is [a, a†] = ____ .", o:["1","i","ħ","0"], a:0, n:"[a, a†] = 1."},
  {p:"If a†|n⟩ ∝ |n+1⟩, then a|n⟩ ∝ ____ .", o:["|n−1⟩","|n+1⟩","|n⟩","zero state"], a:0, n:"a lowers, a† raises."},
  {p:"The energy eigenvalues are Eₙ = ____ .", o:["(n + ½)ħω","nħω","(n − ½)ħω","n²ħω"], a:0, n:"Equally spaced ladder with zero-point ½ħω."}
 ]}
],

/* ---------------- FEYNMAN TEACH-BACK (topics + model answers) ---------------- */
TEACH_TOPICS: [
 {t:"Meissner effect", q:"Explain the Meissner effect as if I were a first-year student.",
  a:"1) Below T_c a superconductor expels magnetic flux from its interior (B = 0 inside). 2) It is a perfect diamagnet with susceptibility χ = −1, not merely a perfect conductor. 3) Surface screening currents flow to cancel the applied field, decaying over the London penetration depth λ. 4) It distinguishes true superconductivity from zero resistance alone."},
 {t:"Wave-particle duality", q:"Explain wave–particle duality.",
  a:"1) Matter and light show both wave and particle behaviour. 2) Particles have a wavelength λ = h/p (de Broglie), so electrons diffract. 3) Detection is always localised (particle-like), while propagation and interference are wave-like. 4) A single object never shows both in the same measurement — the experiment chooses which aspect appears."},
 {t:"Bose–Einstein condensation", q:"Explain Bose–Einstein condensation.",
  a:"1) Below a critical temperature T_c ∝ n^(2/3), a macroscopic fraction of an ideal Bose gas occupies the single ground state. 2) It follows from Bose statistics (any number per state) and the chemical potential reaching the ground-state energy. 3) It is a purely quantum transition with no interactions. 4) Observed in ultracold alkali gases."},
 {t:"Second law of thermodynamics", q:"State and explain the second law of thermodynamics.",
  a:"1) The entropy of an isolated system never decreases. 2) Equivalent forms: Clausius (no spontaneous heat flow from cold to hot) and Kelvin–Planck (no engine converting heat fully to work in a cycle). 3) It sets the arrow of time and the Carnot efficiency ceiling η = 1 − T_c/T_h. 4) Statistically, systems evolve toward more probable (higher-multiplicity) macrostates."},
 {t:"Heisenberg uncertainty principle", q:"Explain the Heisenberg uncertainty principle.",
  a:"1) Conjugate observables cannot both be perfectly sharp: Δx·Δp ≥ ħ/2. 2) It is a property of the wavefunction, not a measurement limitation. 3) It follows from the commutator [x̂,p̂] = iħ via the generalised uncertainty relation ΔA·ΔB ≥ ½|⟨[A,B]⟩|. 4) It also gives the zero-point energy of the harmonic oscillator and the finite width of spectral lines."},
 {t:"Maxwell's equations", q:"State Maxwell's four equations and what each means.",
  a:"1) ∇·E = ρ/ε₀ — charges are the source of E (Gauss). 2) ∇·B = 0 — no magnetic monopoles. 3) ∇×E = −∂B/∂t — changing flux induces E (Faraday). 4) ∇×B = μ₀J + μ₀ε₀∂E/∂t — currents plus the displacement current source B (Ampère–Maxwell); the displacement term makes light possible."},
 {t:"Superposition principle", q:"Explain the quantum superposition principle.",
  a:"1) Any linear combination of allowed states is an allowed state. 2) A system in a superposition has amplitudes for each component; |amplitude|² gives probabilities. 3) Measurement collapses the state to one component. 4) Relative phases matter — they cause interference, the signature quantum effect."},
 {t:"Fermi energy", q:"Explain the Fermi energy.",
  a:"1) The highest occupied single-particle energy at T = 0 in a Fermi gas. 2) E_F = (ħ²/2m)(3π²n)^(2/3) in 3D. 3) Only electrons within ~kT of E_F are thermally active, explaining the small linear electronic heat capacity. 4) It sets the scale for metallic conductivity, Pauli paramagnetism and the Fermi surface."},
 {t:"Why the sky is blue", q:"Explain why the sky is blue (Rayleigh scattering).",
  a:"1) Sunlight is scattered by air molecules much smaller than the wavelength. 2) Rayleigh scattering intensity ∝ 1/λ⁴, so blue scatters far more than red. 3) The scattered blue light reaches us from all directions — the blue sky. 4) At sunset the direct beam loses blue, leaving red — the red sunset."},
 {t:"Photoelectric effect", q:"Explain the photoelectric effect and Einstein's explanation.",
  a:"1) Light ejects electrons from a metal only above a threshold frequency. 2) Einstein: light consists of photons of energy hν; one photon ejects one electron with E_max = hν − φ (work function). 3) This explained why maximum kinetic energy depends on frequency, not intensity, and why emission is instantaneous. 4) It established the photon concept."},
 {t:"de Broglie hypothesis", q:"Explain the de Broglie hypothesis and its significance.",
  a:"1) Matter has a wavelength λ = h/p. 2) It explains the quantisation of Bohr orbits as standing waves (2πr = nλ). 3) Confirmed by electron diffraction (Davisson–Germer). 4) It is the basis of wave mechanics and the Schrödinger equation."},
 {t:"Clausius–Clapeyron equation", q:"Derive and explain the Clausius–Clapeyron equation.",
  a:"1) Along a coexistence curve the chemical potentials of the two phases are equal. 2) dg = −s dT + v dP gives (s₂−s₁)dT = (v₂−v₁)dP. 3) With L = T(s₂−s₁): dP/dT = L/(TΔv). 4) Ice–water has negative slope because ice is less dense (Δv < 0)."},
 {t:"Degenerate perturbation theory", q:"Explain degenerate perturbation theory.",
  a:"1) Used when several states share the same unperturbed energy E₀. 2) First-order corrections are the eigenvalues of ⟨m|H′|n⟩ restricted to the degenerate subspace. 3) The perturbation typically lifts (partially or fully) the degeneracy. 4) The linear Stark effect of hydrogen is the canonical example."},
 {t:"Time-dependent perturbation theory", q:"Explain time-dependent perturbation theory.",
  a:"1) The interaction is turned on for a finite time and the system makes transitions between eigenstates of Ĥ₀. 2) First-order amplitude is c_f = (1/iħ)∫⟨f|H′(t)|i⟩e^{iωt}dt. 3) For a constant matrix element, the probability peaks at ω≈0. 4) Taking the limit of a long time and summing over final states gives Fermi's golden rule."},
 {t:"Addition of angular momentum", q:"Explain how two angular momenta add (Clebsch–Gordan).",
  a:"1) Two momenta j₁ and j₂ combine to total j = |j₁−j₂| … j₁+j₂ in integer steps. 2) Coupled states |jm⟩ are linear combinations of product states |j₁m₁⟩|j₂m₂⟩ with Clebsch–Gordan coefficients. 3) For two spins-½, the triplet (s=1) and singlet (s=0) emerge. 4) Spin–orbit coupling J = L+S uses the same scheme."},
 {t:"Quantum tunnelling", q:"Explain quantum tunnelling.",
  a:"1) A particle can pass through a classically forbidden barrier because the wavefunction decays exponentially inside rather than vanishing. 2) Transmission T ≈ e^(−2κa) with κ = √(2m(V₀−E))/ħ. 3) It explains alpha decay, the tunnel diode, and scanning tunnelling microscopy. 4) The WKB approximation generalises the exponent to arbitrary barrier shapes."},
 {t:"Variational method", q:"Explain the variational method.",
  a:"1) For any trial wavefunction, ⟨H⟩ ≥ E₀ — the expectation value is an upper bound on the ground energy. 2) Choose a physically motivated trial family with parameters. 3) Minimise ⟨H⟩ with respect to the parameters. 4) The minimum is the best variational estimate of E₀."},
 {t:"Ensembles in statistical mechanics", q:"Explain the three statistical ensembles.",
  a:"1) Microcanonical (N,V,E): isolated; all microstates equally probable; S = k ln Ω. 2) Canonical (N,V,T): in a heat bath; pᵢ ∝ e^(−βEᵢ); F = −kT ln Z. 3) Grand canonical (μ,V,T): open; Φ = −kT ln Ξ. 4) All three agree in the thermodynamic limit; fluctuations vanish as 1/√N."},
 {t:"Maxwell relations", q:"Explain the Maxwell relations.",
  a:"1) They come from equality of mixed second derivatives of the thermodynamic potentials. 2) E.g. from dU = TdS − PdV: (∂T/∂V)_S = −(∂P/∂S)_V. 3) They convert hard-to-measure derivatives into measurable response functions. 4) All four follow from U, F, H and G by the same rule."},
 {t:"Carnot theorem", q:"State and prove the idea behind Carnot's theorem.",
  a:"1) No engine between two reservoirs can be more efficient than a reversible Carnot engine. 2) Otherwise two coupled engines would transfer heat from cold to hot with no other effect, violating the second law. 3) Hence η = 1 − T_c/T_h is an absolute ceiling. 4) All reversible engines between the same reservoirs have equal efficiency."},
 {t:"Debye model", q:"Explain the Debye model of specific heat.",
  a:"1) It treats lattice vibrations as sound waves up to a cutoff frequency ω_D. 2) ω_D is set by the total number of modes = 3N. 3) At low T it gives the correct C ∝ T³ law. 4) At high T it recovers Dulong–Petit C = 3R."},
 {t:"Drude model", q:"Explain the Drude model of metals.",
  a:"1) Conduction electrons are treated as a classical gas colliding with a relaxation time τ. 2) Conductivity σ = ne²τ/m and Ohm's law follow. 3) It explains the Wiedemann–Franz law but fails for heat capacity and magnetism. 4) The Sommerfeld model fixes this with Fermi–Dirac statistics."},
 {t:"Semiconductors and band theory", q:"Explain semiconductors using band theory.",
  a:"1) Bands arise from Bloch states in a periodic potential; the gap E_g separates valence and conduction bands. 2) Intrinsic carrier density nᵢ ∝ e^(−Eg/2kT). 3) Donors and acceptors create n-type and p-type conduction. 4) The p-n junction rectifies and underlies diodes, transistors and solar cells."},
 {t:"Bragg diffraction", q:"Explain Bragg's law.",
  a:"1) X-rays reflect from parallel lattice planes. 2) Constructive interference needs the path difference 2d sinθ to equal nλ. 3) It turns a crystal into a 3D diffraction grating, measuring d and hence the lattice. 4) The Laue condition k′−k = G is the equivalent reciprocal-space statement."},
 {t:"Superconductivity (BCS)", q:"Explain superconductivity and BCS theory.",
  a:"1) Below T_c a metal has zero resistance and expels flux (Meissner effect). 2) BCS: phonons bind electrons into Cooper pairs of opposite spin/momentum. 3) Pair condensation opens an energy gap 2Δ and yields T_c ≈ Θ_D e^(−1/N(0)V). 4) The London equations describe flux expulsion with penetration depth λ."},
 {t:"Zeeman effect", q:"Explain the Zeeman effect.",
  a:"1) A magnetic field splits atomic levels by ΔE = g μ_B m_J B. 2) Normal Zeeman (S=0) gives a triplet split by μ_B B. 3) Anomalous Zeeman (S≠0) gives a more complex pattern set by the Landé g-factor. 4) In a very strong field the Paschen–Back regime decouples L and S."},
 {t:"Virial theorem", q:"State and explain the virial theorem.",
  a:"1) For bound systems in equilibrium, 2⟨T⟩ = ⟨r·F⟩. 2) For a power-law potential V ∝ rⁿ it gives 2⟨T⟩ = n⟨V⟩. 3) Gravity/Coulomb (n=−1): 2⟨T⟩ = −⟨V⟩, so E = −⟨T⟩. 4) Used to relate kinetic and potential energies in orbits, atoms and gases."},
 {t:"Normal modes", q:"Explain normal modes of coupled oscillators.",
  a:"1) Small oscillations near equilibrium decompose into independent modes, each with a single frequency. 2) The frequencies come from the eigenvalues of the secular determinant. 3) Normal coordinates diagonalise the kinetic and potential energies. 4) Examples: CO₂ stretching modes, coupled pendulums, phonons."},
 {t:"Fourier transform", q:"Explain the Fourier transform and its role in physics.",
  a:"1) It decomposes a function into plane-wave components, f̃(k) = ∫f(x)e^(−ikx)dx. 2) It diagonalises translation-invariant operators — hence plane-wave eigenstates. 3) It maps between position and momentum space in quantum mechanics (ΔxΔk ≥ ½). 4) Convolution becomes multiplication, which underlies filters and Green's functions."},
 {t:"Residue theorem", q:"Explain the residue theorem and contour integration.",
  a:"1) The integral of f around a closed contour equals 2πi times the sum of residues of enclosed poles. 2) Residues are the a₋₁ coefficients of Laurent expansions. 3) It evaluates real integrals by closing contours in the half-plane. 4) It rests on Cauchy's theorem, which itself follows from analyticity."}
],

/* ---------------- BOSS BATTLES (lane metadata) ---------------- */
BOSS_LANES: [
 {id:"quantum", label:"Quantum Mechanics", emoji:"🧠"},
 {id:"classical", label:"Classical Mechanics", emoji:"⚙️"},
 {id:"emtheory", label:"Electromagnetic Theory", emoji:"⚡"},
 {id:"thermo", label:"Thermodynamics & Statistics", emoji:"🔥"},
 {id:"solidstate", label:"Solid State / Condensed Matter", emoji:"💎"},
 {id:"atnuc", label:"Atomic & Nuclear Physics", emoji:"☢️"},
 {id:"electronics", label:"Electronics", emoji:"🔌"},
 {id:"mathphys", label:"Mathematical Physics", emoji:"📐"}
],

/* ---------------- CAMPAIGN MODE (Class D → Class S) ---------------- */
RANKS: [
 {id:"D", name:"Class D — PROVISIONAL", min:0, emoji:"🟢", story:"The board observes you from a distance. Prove that your presence in this room is not a coincidence."},
 {id:"C", name:"Class C — EVALUEE", min:500, emoji:"🔵", story:"You have begun to move. The system notes your discipline; the first true evaluation has started."},
 {id:"B", name:"Class B — ADEPT", min:1500, emoji:"🟣", story:"Your pattern is no longer random. Peers slow down; you accelerate. The gap is now visible."},
 {id:"A", name:"Class A — ELITE", min:3500, emoji:"🟠", story:"Few reach this floor. Your answers carry weight, and the board speaks your name with interest."},
 {id:"S", name:"Class S — GENIUS", min:7000, emoji:"🔴", story:"The apex of the room. You do not chase the exam anymore — the exam chases you. December awaits its victor."}
]
};
